basePing/Models/Federation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace basePing.Models
{
    public class Federation
    {
        private int     id;
        private string  paysFederation;
        private string  nomFederation;
        private string  web;

        public int Id
        {
            get { return id; }
            set { id = value; }
        }
        public string PaysFederation
        {
            get { return paysFederation; }
            set { paysFederation = value; }
        }
        public string NomFederation
        {
            get { return nomFederation; }
            set { nomFederation = value; }
        }

        public  string Web
        {
            get { return web; }
            set { web = value; }
        }

        public Federation() { }
        public Federation(int id, string paysFederation, string nomFederation, string web)
        {
            this.id = id;
            this.paysFederation = paysFederation;
            this.nomFederation = nomFederation;
            this.web = web;
        }
        public List<Federation> GetList()
        {
            List<Federation> liste = new List<Federation>();
            DataContext.DCFederation federation = new DataContext.DCFederation();
            return liste = federation.GetAllFederation();
        }
        public Federation GetFederation(int id)
        {
            Federation federation = new Federation();
            DataContext.DCFederation fede = new DataContext.DCFederation();
            return federation = fede.GetFederation(id);
        }
        public void AddFederation(string nomFederation, string pays, string web)
        {
            DataContext.DCFederation federation = new DataContext.DCFederation();
            string Pays = federation.GetPays(pays);
            federation.AddFederation(nomFederation , Pays, web);
        }
        public void DeleteFederation(int id)
        {
            DataContext.DCFederation federation = new DataContext.DCFederation();
            federation.DelFederation(id);
        }
        public void UpdateFederation(int id, string nomFedePays, int? pays, string web)
        {
            DataContext.DCFederation federation = new DataContext.DCFederation();
            string Pays = federation.GetPays(pays);
            federation.UpdateFederation(id,nomFedePays,Pays,web);
        }
    }

}

basePing/Controllers/FederationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using basePing.Models;
using basePing.DataContext;

namespace basePing.Controllers
{
    public class FederationController : Controller
    {
        // GET: Federation
        public ActionResult Index()
        {
            List<Federation> listeFederation = new List<Federation>();
            Federation federation = new Federation();
            listeFederation = federation.GetList();
            ViewBag.liste = listeFederation;
            return View();
        }


        [Authorize]
        public ActionResult AddFederation(string nomFederation, int? Pays, string web)
        {
            string pays = Pays.ToString();
            Federation federation = new Federation();
            nomFederation = HttpUtility.HtmlEncode(nomFederation);
            web = HttpUtility.HtmlEncode(web);
            if (Pays != null && nomFederation != "" && web != "")
            {
                federation.AddFederation(nomFederation, pays, web);
                return Redirect("Index");
            }
            else
            {
                return Redirect("Index?error=Tous les champs doivent être complétés");
            }
        }


        [Authorize]
        public ActionResult UpdateFederation(int id)
        {
            Federation federation = new Federation();
            List<CPays> listP = new CPays().GetListPays();
            CPays pays = null;
      
            federation = federation.GetFederation(id);
            foreach (CPays P in listP)
            {
                if (P.Pays == federation.PaysFederation)
                {
                    pays = P;
                }
            }
            listP.Insert(0, pays);
       
            Session["listP"] = new SelectList(listP,"Id","Pays");
            return View(federation);
        }


        [Authorize]
        public ActionResult UpdateFede(int id, string nomFederation, int? Pays, string web)
        {
            nomFederation = HttpUtility.HtmlEncode(nomFederation);
            web = HttpUtility.HtmlEncode(web);
            if (Pays != null && nomFederation != "")
            {
                Federation federation = new Federation();
                federation.UpdateFederation(id, nomFederation, Pays, web);
                return Redirect("Index");
            }
            else
            {
                return Redirect("UpdateFederation/"+ id + "/?error=Tous les champs doivent être complétés");
            }
            
        }


        [Authorize]
        public ActionResult DeleteFederation(int id)
        {
            Federation federation = new Federation();
            federation.DeleteFederation(id);
            return Redirect("~/Federation/Index");
        }
    }
}

basePing/Views/Federation/Index.cshtml
@using basePing.Models;
@{
    ViewBag.Title = "liste des fédérations";
}
@if ((bool)Session["admin"])
{
    <br />
    <div class="form-inline">
        @using (Html.BeginForm("AddFederation", "Federation"))
        {
            <div class="form-group">
                <label>Fédération </label>
                <input type="text" class="form-control" name="nomFederation">
            </div>

            <div class="form-group">
                <label>Nationalité </label>
                @Html.DropDownList("Pays", Session["listePays"] as SelectList, string.Empty, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Lien du site</label>
                <input type="text" class="form-control" name="web">
            </div>
            <br />
            <br />
            <input type="submit" class="btn btn-success" value="Ajouter" />
        }
    </div>
    <div>
        <h2 class="alert-danger">@Request.QueryString["error"]</h2>
    </div>
}
<h2>@ViewBag.Title</h2>
<div>
    <br />
    <table class="table table-striped">
        @foreach (Federation f in ViewBag.liste)
        {
            <tr class="bg-info">
                <td>@HttpUtility.HtmlDecode(f.NomFederation)</td>
                <td>@f.PaysFederation</td>
                <td><a href="http://\@HttpUtility.HtmlDecode(f.Web)" class="btn btn-primary active" role="button" target="_blank">@HttpUtility.HtmlDecode(f.Web)</a></td>
                @if ((bool)Session["admin"])
                {
                    <td>@Html.ActionLink("Modifier", "UpdateFederation", "Federation", new { id = f.Id }, new { @class = "btn btn-info" })</td>
                    <td>@Html.ActionLink("Effacer", "DeleteFederation", "Federation", new { id = f.Id }, new { @class = "btn btn-danger", onclick = "return confirm('Confirmez-vous la suppression?')" })</td>
                }
            </tr>
        }
    </table>
</div>

basePing/Views/Federation/UpdateFederation.cshtml
@model basePing.Models.Federation
@{
    ViewBag.Title = "Update Federation";
}

<h2>Mise à jour fédération</h2>
<br />
<div class="form-inline">
    @using (Html.BeginForm("UpdateFede", "Federation"))
    {
        <div class="form-group">
            <input type="text" class="hidden" name="id" value="@Model.Id">
            <label>Fédération </label>
            <input type="text" class="form-control" name="nomFederation" value="@HttpUtility.HtmlDecode(Model.NomFederation)">
        </div>

            <div class="form-group">
                <label>Nationalité </label>
                @Html.DropDownList("Pays", Session["listP"] as SelectList , new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Lien du site</label>
                <input type="text" class="form-control" name="web" value="@HttpUtility.HtmlDecode(Model.Web)">
            </div>
            <br />
            <br />
            <input type="submit" class="btn btn-success" value="Modifier" />
            <br />
            <br />
            @Html.ActionLink("Annuler", "Index", "Federation", null, new { @class = "btn btn-info" })
    }
</div>
<div>
    <h2 class="alert-danger">@Request.QueryString["error"]</h2>
</div>