basePing/Models/Serie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace basePing.Models
{
    public class Serie
    {
        private int id;
        private string descriptif = "pas de description";

        public int Id {get{return id;}set{ id = value; }}
        public string Descriptif { get{ return descriptif; }set{ descriptif = value; } }

        public Serie(int id,string descriptif)
        {
            this.id = id;
            this.descriptif = descriptif;
        }

        public Serie()
        {
        }

        public Serie(int id)
        {
            this.id = id;
        }
    }
}

basePing/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using basePing.Models;
using basePing.DataContext;

namespace basePing.Controllers
{
    public class MatchController : Controller
    {
        // GET: Match
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult InfoMatch(int id)
        {
            Match m = new DCMatch().find(id);
            m.Joueur1.RecupererJoueur();
            m.Joueur2.RecupererJoueur();
            m.LSet = new Set().GetList(id);
            return View(m);
        }

        public ActionResult InfoMatchDouble(int id)
        {
            MatchDouble m = new DCMatch().findDouble(id);
            m.Joueur1.RecupererJoueur();
            m.Joueur2.RecupererJoueur();
            m.Joueur3.RecupererJoueur();
            m.Joueur4.RecupererJoueur();
            m.LSet = new Set().GetList(id);
            return View(m);
        }

        [Authorize]
        public ActionResult AjoutSet(int idM, int cpt1, int cpt2, int score1,int  score2,string j1,string j2)
        {
            Session["cpt1"] = cpt1;
            Session["cpt2"] = cpt2;
            Session["score1"] = score1;
            Session["score2"] = score2;
            Session["j1"] = j1;
            Session["j2"] = j2;
            ViewBag.j1 = j1;
            ViewBag.j2 = j2;
            Session["idM"] = idM;
            return View();
        }


        [Authorize]
        public ActionResult AjoutSetDouble(int idM, int cpt1, int cpt2, int score1, int score2, string j1, string j2,string j3,string j4)
        {
            Session["cpt1"] = cpt1;
            Session["cpt2"] = cpt2;
            Session["score1"] = score1;
            Session["score2"] = score2;
            Session["j1"] = j1;
            Session["j2"] = j2;
            Session["j3"] = j3;
            Session["j4"] = j4;

            ViewBag.j1 = j1;
            ViewBag.j2 = j2;
            ViewBag.j3 = j3;
            ViewBag.j4 = j4;
            Session["idM"] = idM;
            return View();
        }


        [Authorize]
        public ActionResult SupprimerSet(int idS,int idM)
        {
            DCSet dc = new DCSet();
            dc.Delete(idS);
            return Redirect("~/Match/InfoMatch/" + idM);
        }

        [Authorize]
        public ActionResult SupprimerSetDouble(int idS, int idM)
        {
            DCSet dc = new DCSet();
            dc.Delete(idS);
            return Redirect("~/Match/InfoMatchDouble/" + idM);
        }



        [Authorize]
        [HttpPost]
        public ActionResult AjoutSet(int position,int point1, int point2)
        {
            DCSet dc = new DCSet();

            if (dc.findSamePos(position, (int)Session["idM"]))
            {
                return Redirect("/Match/AjoutSet?idM="+ (int)Session["idM"] + "&cpt1="+ (int)Session["cpt1"] + "&cpt2="+ (int)Session["cpt2"] + "&score1="+(int)Session["score1"]+"&score2="+ (int)Session["score1"] + "&j1="+HttpUtility.HtmlEncode(Session["j1"]) + "&j2="+ HttpUtility.HtmlEncode(Session["j2"])+"&error=Il existe déja un set sur cette position");
            }

            if (point1> point2 && (int)Session["cpt1"]< (int)Session["score1"])
            {
                dc.Insert((int)Session["idM"], point1, point2,position);
                return Redirect("/Match/InfoMatch/" + Session["idM"]);
            }else if (point2 > point1 && (int)Session["cpt2"] < (int)Session["score2"])
            {
                dc.Insert((int)Session["idM"], point1, point2,position);
                return Redirect("/Match/InfoMatch/" + Session["idM"]);
            }
            else
                return Redirect("~/Match/InfoMatch/"+Session["idM"]+"?error=Erreur le gagnant du match ne correspond pas au nombre de set gagné");


        }

        [Authorize]
        [HttpPost]
        public ActionResult AjoutSetDouble(int position, int point1, int point2)
        {
            DCSet dc = new DCSet();

            if (dc.findSamePos(position, (int)Session["idM"]))
            {
                return Redirect("/Match/AjoutSetDouble?idM=" + (int)Session["idM"] + "&cpt1=" + (int)Session["cpt1"] + "&cpt2=" + (int)Session["cpt2"] + "&score1=" + (int)Session["score1"] + "&score2=" + (int)Session["score1"] + "&j1=" + HttpUtility.HtmlEncode(Session["j1"]) + "&j2=" + HttpUtility.HtmlEncode(Session["j2"]) + "&j3=" + HttpUtility.HtmlEncode(Session["j3"])+"&j4="+ HttpUtility.HtmlEncode(Session["j4"])+"& error=Il existe déja un set sur cette position");
            }

            if (point1 > point2 && (int)Session["cpt1"] < (int)Session["score1"])
            {
                dc.Insert((int)Session["idM"], point1, point2, position);
                return Redirect("/Match/InfoMatchDouble/" + Session["idM"]);
            }
            else if (point2 > point1 && (int)Session["cpt2"] < (int)Session["score2"])
            {
                dc.Insert((int)Session["idM"], point1, point2, position);
                return Redirect("/Match/InfoMatchDouble/" + Session["idM"]);
            }
            else
                return Redirect("~/Match/InfoMatchDouble/" + Session["idM"] + "?error=Erreur le gagnant du match ne correspond pas au nombre de set gagné");


        }


        [Authorize]
        public ActionResult AjoutMatch(int id)
        {
            ViewBag.idComp = id;
            List<Joueur> j = new Joueur().GetListJoueurComp(id);
            Session["listJ"] = new SelectList(j, "Id", "Identite");
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AjoutMatch(int id,int? joueur1,int score1,int? joueur2,int score2)
        {
            DCMatch dc = new DCMatch();
            if (joueur1 == joueur2)
                return Redirect("/Match/AjoutMatch?id=" + id +"&error=Les 2 joueurs choisis sont le même.");
            else
            {

                dc.Create(id, joueur1, score1, joueur2, score2);

                return Redirect("~/Competition/InfoComp/" + id);
            }
        }



        [Authorize]
        public ActionResult AjoutMatchEquipe(int id)
        {
            ViewBag.idComp = id;
            List<Equipe> j = new Equipe().GetListEquipeComp(id);
            Session["listE"] = new SelectList(j, "Id", "Nom");
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AjoutMatchEquipe(int id, int? equipe1, int score1, int? equipe2, int score2)
        {
            DCMatch dc = new DCMatch();
            if (equipe1 == equipe2)
                return Redirect("/Match/AjoutMatch?id=" + id + "&error=Les 2 joueurs choisis sont le même.");
            else
            {

                dc.CreateEquipe(id, equipe1, score1, equipe2, score2);

                return Redirect("~/CompetitionEquipe/InfoComp/" + id);
            }
        }


        [Authorize]
        public ActionResult SuppMatch(int id)
        {
            DCMatch dc = new DCMatch();
            dc.Delete(id);
            return Redirect("~/Competition/InfoComp/"+ Session["idComp"]);
        }


        [Authorize]
        public ActionResult LieMatch(int pos,int idC,int idS)
        {
            Session["pos"] = pos;
            Session["idC"]= idC;
            Session["idS"] = idS;
            List<Joueur> listJ = new Joueur().GetListJoueurComp(idC);
           
            List<Match> listM = new Match().GetMatchComp(idC);
            foreach (Match m in listM)
            {
                m.Joueur1.RecupererJoueur();
                m.Joueur2.RecupererJoueur();
            }
            Session["listJ"] = new SelectList(listJ, "Id", "Identite");
            Session["listM"] = new SelectList(listM, "Id", "Info");
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult LieMatch(int match)
        {
            DCMatch dc = new DCMatch();
            dc.LinkMatch((int)Session["pos"],(int) Session["idS"],(int)Session["idC"],match);
            return Redirect("~/Competition/InfoComp/" + Session["idComp"]);
        }

        [Authorize]
        public ActionResult LieMatchPoule(int idJ, int idC, int idS)
        {
            Session["idC"] = idC;
            Session["idS"] = idS;
            Session["pos"] = 0;
            Joueur jToRemove = null;
            List<Joueur> listJ = new Joueur().GetListJoueurComp(idC);
            foreach (Joueur j in listJ)
            {
                if (j.Id == idJ)
                    jToRemove = j;
            }
            listJ.Remove(jToRemove);
            List<Match> listM = new Match().GetMatchComp(idC,idJ);
            foreach (Match m in listM)
            {
                m.Joueur1.RecupererJoueur();
                m.Joueur2.RecupererJoueur();
            }
            Session["listJ"] = new SelectList(listJ, "Id", "Identite");
            Session["listM"] = new SelectList(listM, "Id", "Info");
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult LieMatchPoule(int match)
        {
            DCMatch dc = new DCMatch();
            dc.LinkMatch((int)Session["pos"], (int)Session["idS"], (int)Session["idC"],match);
            return Redirect("~/Competition/InfoComp/" + Session["idComp"]);
        }


        [Authorize]
        [HttpPost]
        public ActionResult AjoutEtLieMatch(int? joueur1, int score1, int? joueur2, int score2)
        {
            DCMatch dc = new DCMatch();
           
            if (joueur1 == joueur2)
                return Redirect("/Match/LieMatch?pos="+ (int)Session["pos"] + "&idC="+ (int)Session["idComp"] + "&idS="+ (int)Session["idS"] + "&error=Les 2 joueurs choisis sont le même.");
            else { 
                dc.Create(joueur1, score1, joueur2, score2, (int)Session["pos"], (int)Session["idS"], (int)Session["idComp"]);
                return Redirect("~/Competition/InfoComp/" + Session["idComp"]);

basePing/Controllers/SerieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using basePing.DataContext;
using basePing.Models;

namespace basePing.Controllers
{
    public class SerieController : Controller
    {
        // GET: Serie
        public ActionResult Index()
        {
          
            return View();
        }


        [Authorize]
        [HttpPost]
        public ActionResult AjoutPoule(string nom , int taille , int idComp)
        {
            DCPoule dc = new DCPoule();
            dc.Create(nom,taille,idComp);
            return Redirect("~/Competition/InfoComp/" + idComp);
        }

        [Authorize]
        public ActionResult ModifPouleForm(int idC, int id,string desc,string nom,int taille)
        {
            Poule p = new Poule(id, HttpUtility.HtmlEncode(desc),taille, HttpUtility.HtmlEncode(nom));
            Session["idC"] = idC;
            return View(p);
        }

        [Authorize]
        [HttpPost]
        public ActionResult ModifPoule(int id, string nom, string desc, int taille)
        {
            Poule p = new Poule(id, HttpUtility.HtmlEncode(desc), taille, HttpUtility.HtmlEncode(nom));
            DCPoule dc = new DCPoule();
            dc.Update(p);
            return Redirect("~/Competition/InfoComp/" + Session["idC"]);
        }

        [Authorize]
        public ActionResult SuppPoule(int id,int idC)
        {
           
            DCPoule dc = new DCPoule();
            dc.Delete(id);
            return Redirect("~/Competition/InfoComp/" + idC);
        }


        [Authorize]
        public ActionResult SuppPhaseFinale(int id, int idC)
        {

            DCTournoi dc = new DCTournoi();
            dc.Delete(id);
            return Redirect("~/Competition/InfoComp/" + idC);
        }

        [Authorize]
        public ActionResult AjouterTournoi(int id)
        {
            ViewBag.idComp = id;
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AjouterPhaseFinale(int id,int taille)
        {
            DCTournoi dc = new DCTournoi();
            dc.Create(id,taille, HttpUtility.HtmlEncode(""));
            return Redirect("~/Competition/InfoComp/" + id);
        }

        public ActionResult ListMatchPoule(int idP ,int idC ,int IdJ)
        {
            Session["idC"] = idC;
            Session["idS"] = idP;
            Session["idJ"] = IdJ;
            List<Match> listM = new Match().GetListMatch(idP,IdJ);
            foreach (Match m in listM)
            {
                m.Joueur1.RecupererJoueur();
                m.Joueur2.RecupererJoueur();
            }
            Session["listM"] =listM;
            return View();
        }


        public ActionResult ListRencontrePouleEquipe(int idP, int idC, int IdE)
        {
            Session["idC"] = idC;
            Session["idS"] = idP;
            Session["idE"] = IdE;
            List<MatchEquipe> listM = new MatchEquipe().GetListMatch(idP, IdE);
            foreach (MatchEquipe m in listM)
            {
                m.Equipe1.RecupererEquipe();
                m.Equipe2.RecupererEquipe();
            }
            Session["listR"] = listM;
            return View();
        }
    }
}

basePing/Views/Serie/AjouterTournoi.cshtml
@using (Html.BeginForm("AjouterPhaseFinale", "Serie"))
{

    <input type="hidden" value="@ViewBag.idComp" name="id" />
    <label>Taille</label>
    <input type="number" name="taille" min="1" max="5" required="required" />

  

    <input type="submit" value="Ajouter" />

}

basePing/Views/Serie/ListMatchPoule.cshtml
@using basePing.Models;

<h2>Liste des Match du poule</h2>

<table border="1">
    <tr><th>Joueur 1</th><th>Score du joueur 1</th><th>VS</th><th>Score du joueur 2</th><th>Joueur 2</th></tr>
    @foreach (Match m in (List<Match>)Session["listM"])
    {
      
        <tr><td>@m.Joueur1.Nom</td><td>@m.Score1</td><td>VS</td><td>@m.Score2</td><td>@m.Joueur2.Nom</td>
    @if (new Set().GetList(m.Id).Count != 0 && (bool)Session["admin"] == false)
    {
    <td>@Html.ActionLink("Détail", "InfoMatch", "Match", new { id = m.Id }, null)</td><td>
        @if ((bool)Session["admin"])
        {
            @Html.ActionLink("Supprimer", "SuppMatch", "Match", new { id = m.Id }, new { @class = "btn btn-success", onclick = "return confirm('Etes vous sur de vouloir supprimer ce match')" })
        }</td>

    }</tr>
    }
</table>
@if ((bool)Session["admin"])
{
    <td>@Html.ActionLink("Ajouter Match", "LieMatchPoule", "Match", new { idJ = Session["idJ"], idC = Session["idC"], idS = Session["idS"] }, new { @class = "btn btn-success" })
</td>
}

<div>
    @Html.ActionLink("Retour", "InfoComp/" + Session["idComp"],"Competition", new { area = "" }, new { @class = "btn btn-danger" })

</div>

basePing/Views/Serie/ListRencontrePouleEquipe.cshtml
@using basePing.Models;

<h2>Liste des rencontres du poule</h2>

<table border="1">
    <tr><th>Equipe 1</th><th>Point de l'équipe 1</th><th>VS</th><th>Poin de l'équipe 2</th><th>Equipe 2</th></tr>
    @foreach (MatchEquipe m in (List<MatchEquipe>)Session["listR"])
    {

        <tr>
            <td>@m.Equipe1.Nom</td>
            <td>@m.Score1</td>
            <td>VS</td>
            <td>@m.Score2</td>
            <td>@m.Equipe2.Nom</td>
            <td>@Html.ActionLink("Détail matchs de l' équipe", "InfoRencontre", "CompetitionEquipe", new { id = m.Id }, null)</td>
            <td>
                @if ((bool)Session["admin"])
                {
                    @Html.ActionLink("Supprimer", "SuppRencontreEquipe", "CompetitionEquipe", new { id = m.Id }, new { @class = "btn btn-success", onclick = "return confirm('Etes vous sur de vouloir supprimer ce match')" })
                }
            </td>
        </tr>
    }
</table>
@if ((bool)Session["admin"])
{
    <td>
        @Html.ActionLink("Ajouter une rencontre d' équipe", "LieRencontrePoule", "CompetitionEquipe", new { idE = Session["idE"], idC = Session["idC"], idS = Session["idS"] }, new { @class = "btn btn-success" })
</td>
}

<div>
    @Html.ActionLink("Retour", "InfoComp/" + Session["idComp"], "Competition", new { area = "" }, new { @class = "btn btn-danger" })

</div>

basePing/Views/Serie/ModifPouleForm.cshtml
@model basePing.Models.Poule


@using (Html.BeginForm("ModifPoule", "Serie"))
{

    <input type="hidden" value="@Model.Id" name="id" />
    <label>Nom</label>
    <input type="text" name="nom" value="@Model.NomPoule" required="required" />
    <label>Descriptif</label>
    <input type="text" name="desc" value="@Model.Descriptif" required="required" />
    <label>Taille</label>
    <input type="number" name="taille" value="@Model.Taille" required="required" />

    <input type="submit" value="Modifier" />

}