basePing/Models/Competition.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using basePing.DataContext;

namespace basePing.Models
{
    public class Competition
    {
        private int id;
        private string nom;
        private DateTime dateDeb;
        private DateTime dateFin;
        private string typeComp;
        private string nbrJoueur;
        private CPays pays;
        private Categorie cat;
        private SousCategorie sousCat;
        private List<Poule> lPoule= new List<Poule>();
        private Tournoi tournoi=null;


        public int Id { get{ return id; } set { id = value; } }
        public string Nom { get { return HttpUtility.HtmlDecode(nom); } set { nom = value; } }
        public DateTime DateDeb { get { return dateDeb; } set { dateDeb = value; } }
        public DateTime DateFin { get { return dateFin; } set { dateFin = value; } }
        public CPays Pays { get { return pays;  } }
        

        public string TypeComp { get { return HttpUtility.HtmlDecode(typeComp); } set { typeComp = value; } }
        public string NbrJoueur { get { return HttpUtility.HtmlDecode(nbrJoueur); } set { nbrJoueur = value; } }
        public Categorie Cat { get { return cat; } set { cat = value; } }
        public SousCategorie SousCat { get { return sousCat; } set { sousCat = value; } }
        public List<Poule> LPoule{ get { return lPoule; } set { lPoule = value; } }
        public Tournoi Tournoi { get { return tournoi; } set { tournoi = value; } }


        public Competition(int id, string nom, DateTime dateDeb,DateTime dateFin, string typeComp,string nbrJoueur,Categorie cat, SousCategorie sousCat,CPays pays)
        {
            this.id = id;
            this.nom = nom;
            this.dateDeb = dateDeb;
            this.dateFin = dateFin;
            this.typeComp = typeComp;
            this.cat = cat;
            this.sousCat = sousCat;
            this.nbrJoueur = nbrJoueur;
            this.pays = pays;

        }

        public Competition()
        {
        }


        public Competition(int id)
        {
            this.id = id;
        }

        public Competition(int id, string nom, DateTime dateDeb, DateTime dateFin, string typeComp, string nbrJoueur,CPays pays)
        {

            this.id = id;
            this.nom = nom;
            this.dateDeb = dateDeb;
            this.dateFin = dateFin;
            this.typeComp = typeComp;
            this.nbrJoueur = nbrJoueur;
            this.pays = pays;

        }

        public Competition GetInformation()
        {
            DCCompetition dc = new DCCompetition();
            Competition comp= dc.find(id);
            
            Poule p = new Poule();
            comp.Tournoi = new DCTournoi().find(id);
            if (comp.NbrJoueur == "Individuel")
            {
                comp.LPoule = p.GetListPoule(id);
                
            }else if (comp.NbrJoueur == "Equipe")
            {

                comp.LPoule = p.GetListPouleEquipe(id);

            }
            if (comp.Tournoi!=null)
                comp.Tournoi.GetListMatch(comp.nbrJoueur);
            return comp;
        }

        internal List<Competition> GetListTrie(string nom, int? an, string sexe, string nbrJ,int idSousCat)
        {
            DCCompetition dc = new DCCompetition();
            return dc.FindListTrie(nom, an,sexe,nbrJ,idSousCat);
        }

        public String GetVainqueur()
        {
            DCJoueur dc = new DCJoueur();
            DCEquipe dc2 = new DCEquipe();
            Joueur j = null;
            Equipe e = null;
            if (nbrJoueur == "Individuel")
            {
                j = dc.FindVainqueur(id);
                if(j!=null)
                    return j.Identite;

            }
            else if (nbrJoueur == "Equipe")
            {
                e = dc2.FindVainqueur(id);
                if (e != null)
                    return e.Nom;
            }
            return "Pas de vainqueur désigné";
        }

        public List<Competition> GetList()
        {
            DCCompetition dc = new DCCompetition();
            return dc.findAll();
        }

        public List<Competition> GetListNoSousCat(int id)
        {
            DCCompetition dc = new DCCompetition();
            return dc.findAllCompNoCat(id);
        }
        public void GetTournoi()
        {
            tournoi = new DCTournoi().find(id);
        }

        public List<Joueur> GetListPart()
        {
            DCJoueur dc = new DCJoueur();
            return dc.findAllComp(id);
        }


        public List<Equipe> GetListEquipe()
        {
            DCEquipe dc = new DCEquipe();
            return dc.findAllComp(id);
        }
    }
}

basePing/Models/SousCategorie.cs
using basePing.DataContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace basePing.Models
{
    public class SousCategorie
    {
        private int id;
        private string nom;



        public int Id { get { return id; } set { id = value; } }
        public string Nom { get { return HttpUtility.HtmlDecode(nom); } set { nom = value; } }

        public SousCategorie(int id, string nom)
        {
            this.id = id;
            this.nom = nom;
        }

        public SousCategorie()
        {
        }

        public  List<SousCategorie> GetList(int id)
        {
            DCSousCategorie dc = new DCSousCategorie();
            return dc.findAll(id);
        }
    }
}

basePing/Controllers/CompetitionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using basePing.Models;
using basePing.DataContext;
using basePing.ViewModel;

namespace basePing.Controllers
{
    public class CompetitionController : Controller
    {
        // GET: Competition
        public ActionResult Index()
        {

            return View();
        }

        [Authorize]
        public ActionResult AjouterSousCatForm()
        {
            return View();
        }

        [Authorize]
        public ActionResult AjouterSousCat(string nom)
        {
            DCSousCategorie dc = new DCSousCategorie();
            dc.Insert(HttpUtility.HtmlEncode(nom),(int)Session["idC"]);
            return Redirect("SousCategorie/" + Session["idC"]);
        }


        [Authorize]
        public ActionResult ModifSousCatForm(int idSC,string nom)
        {
            ViewBag.idSC = idSC;
            ViewBag.Nom = nom;


            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult ModifSousCat(int id,string nom)
        {
            DCSousCategorie dc = new DCSousCategorie();
            dc.Update(id,nom);
            return Redirect("SousCategorie/" + Session["idC"]);

        }


        public ActionResult SousCategorie(int id)
        {
            Session["idC"] = id;
            SousCategorie Scat = new SousCategorie();
            Categorie cat = new DCCategorie().find(id);
            ViewBag.Cat = cat;
            ViewBag.sousCat=Scat.GetList(id);
            return View();
        }

        public ActionResult GetComp(int id)
        {
            
            Session["idSC"] = id;
            
            Competition comp = new Competition();
            if (id != -1) { 
            List<CPays> listePays = new CPays().GetListPays();
            Session["listePays"] = new SelectList(listePays, "Id", "Pays");
            List<Competition> triedList = new List<Competition>();
            foreach (Competition c in comp.GetList())
            {
                if (c.SousCat.Id== id) {
                    c.GetTournoi();
                    triedList.Add(c);
                }
            }
            foreach(Categorie c in Categorie.GetList())
            {
                if (c.Id == (int)Session["idC"])
                    ViewBag.cat = c;
            }
            ViewBag.listComp = triedList;
            }
            return View();
        }

        public ActionResult InfoComp(int id)
        {
            Session["Url"] = Request.Url.LocalPath.ToString();
            Session["idComp"] = id;
            Competition comp = new Competition(id);
            comp = comp.GetInformation();

            Session["CPays"] = comp.Pays;
            if (comp.NbrJoueur== "Individuel")
            { 
                return View(comp);
            }
            else if (comp.NbrJoueur == "Equipe")
                return Redirect("~/CompetitionEquipe/InfoComp/"+id);
            return null;
        }

        [Authorize]
        public ActionResult AjouterTypeCompForm()
        {
            return View();
        }

        [Authorize]
        public ActionResult AjouterTypeComp(string nom,string desc)
        {
            DCCategorie dc = new DCCategorie();
            dc.Insert(nom, desc);
            return Redirect("~/Home/Connect");
        }

        [Authorize]
        public ActionResult ModifCat(int id)
        {
            ViewBag.idCat = id;
            return View();
        }

        [Authorize]
        public ActionResult SuppSousCat(int idSC)
        {
            DCSousCategorie dc = new DCSousCategorie();
            dc.Delete(idSC);

            return Redirect("SousCategorie/"+Session["idC"]);
        }

        [Authorize]
        [HttpPost]
        public ActionResult ModifCat(int id, string nom , string desc)
        {
            DCCategorie dc = new DCCategorie();
            dc.Update(HttpUtility.HtmlEncode(nom), HttpUtility.HtmlEncode(desc),id);
            return Redirect("~/Home/Connect");
        }

        [Authorize]
        public ActionResult SuppCat(int id)
        {
            DCCategorie dc = new DCCategorie();
            dc.Delete(id);
            return Redirect("~/Home/Connect");
        }

        [Authorize]
        public ActionResult AjoutComp(int id,int idSC)
        {
            Session["idSC"] = idSC;
            List<CPays> listePays = new CPays().GetListPays();
            List<String> listeType = new List<String>();
            listeType.Add("Masculin");
            listeType.Add("Féminin");
            listeType.Add("Mixte");
            List<String> listeNbrJ= new List<String>();
            listeNbrJ.Add("Individuel");
            listeNbrJ.Add("Equipe");
            ViewBag.listePays = new SelectList(listePays, "Id", "Pays");
            ViewBag.listeType = new SelectList(listeType);
            ViewBag.listeNbrJ = new SelectList(listeNbrJ);
            ViewBag.idCat = id;
            return View();
        }



        [Authorize]
        [HttpPost]
        public ActionResult AjoutComp(String nom, DateTime dateD, DateTime dateF, string pays, string type, string nbrJ, int idCat)
        {
            DCCompetition dc = new DCCompetition();
            dc.Insert(HttpUtility.HtmlEncode(nom), dateD, dateF, pays, HttpUtility.HtmlEncode(type), HttpUtility.HtmlEncode(nbrJ), idCat, (int)Session["idSC"]);
            return Redirect("~/Competition/GetComp/"+ Session["idSC"]);
        }

        [Authorize]
        public ActionResult ModifierComp(int id, string nom, DateTime dateD, DateTime dateF, string type, string nbrJ,int idc)
        {
            SousCategorie sc = new SousCategorie();
            List<SousCategorie> lSC = new List<SousCategorie>();
            lSC = sc.GetList(idc);
            List<CPays> listePays = new CPays().GetListPays();
            listePays.Insert(0, (CPays)Session["CPays"]);
            List<String> listeType = new List<String>();
            listeType.Add(type);
            listeType.Add("Masculin");
            listeType.Add("Féminin");
            listeType.Add("Mixte");
            List<String> listeNbrJ = new List<String>();
            listeNbrJ.Add(nbrJ);
            listeNbrJ.Add("Individuel");
            listeNbrJ.Add("Equipe");
            ViewBag.listeSC = new SelectList(lSC, "Id", "Nom");
            ViewBag.listePays = new SelectList(listePays, "Id", "Pays");
            ViewBag.listeType = new SelectList(listeType);
            ViewBag.listeNbrJ = new SelectList(listeNbrJ);
            ViewBag.Nom = nom;
            ViewBag.dateD = dateD;
            ViewBag.dateF = dateF;
            ViewBag.idComp = id;
            return View();
        }


        [Authorize]
        [HttpPost]
        public ActionResult ModifierComp(String nom, DateTime dateD, DateTime dateF, string pays, string type, string nbrJ,int idSC,int idComp)
        {
            DCCompetition dc = new DCCompetition();
            dc.Update(idComp, HttpUtility.HtmlEncode(nom), dateD, dateF, pays, HttpUtility.HtmlEncode(type), HttpUtility.HtmlEncode(nbrJ),idSC);
            return Redirect("~/Competition/InfoComp/" + idComp);
        }

        [Authorize]
        public ActionResult SuppressionComp(int id)
        {
            DCCompetition dc = new DCCompetition();
            dc.Delete(id);
            return Redirect("~/Home/Connect");
        }



        [Authorize]
        public ActionResult AjoutParticipant()
        {
            // Liste des participants de la compétition
            int idC = Convert.ToInt32(Session["idComp"]);
            DCJoueur dCJoueur = new DCJoueur();
            Joueur participant = new Joueur();
            Joueur joueur = new Joueur();
            List<VMParticipant> listeParticipant = new List<VMParticipant>();
            foreach(Joueur j in participant.GetListJoueurComp(idC))
            {
                VMParticipant mParticipant = new VMParticipant();
                joueur =dCJoueur.GetJoueur(j.Id);
                mParticipant.Id = joueur.Id;
                mParticipant.Nom = joueur.Nom;
                mParticipant.Prenom = joueur.Prenom;
                mParticipant.National = joueur.National;
                mParticipant.Position = Convert.ToString(dCJoueur.GetPositionComp(joueur.Id, idC));
                if(mParticipant.Position == "100")
                {
                    mParticipant.Position = "Pas classé(e)";
                }
                listeParticipant.Add(mParticipant);
            }
            ViewBag.listeParticipant = listeParticipant;
            return View();
        }




        [HttpPost]
        public ActionResult ListeParticipant(string nom, int? pays, string sexe)
        {
            // Initialisation
            char sex = 'f';
            DCJoueur joueur = new DCJoueur();
            List<Joueur> listeJoueur = new List<Joueur>();
            ViewBag.alerte = 0;
            ViewBag.Message = null;
            // Vérification du sexe
            if (sexe == "Masculin")
            {
                sex = 'm';
            }

            // Appel des listes de joueurs selon les attribut sélectionnés
            // 1) Nom est rempli
            if (nom != "")
            {
                // Pays remplis , sexe vide (Vérifier)
                if (pays != null && sexe == "")
                {
                    listeJoueur = joueur.GetJoueurByNameAndCountry(nom, pays);
                    if (listeJoueur.Count() != 0)
                    {
                        ViewBag.listeJoueur = listeJoueur;
                    }
                    else
                    {
                        return Redirect("~/Competition/AjoutParticipant/" + Session["idComp"] + "?error=Aucune information trouvée");
                    }
                }
                // Pays vide , sexe remplis
                if (pays == null && sexe != "")
                {

basePing/Views/Competition/AddNewJoueur.cshtml
@{
    ViewBag.Title = "AddNewJoueur";
}

<h2>Créer un nouveau joueur/joueuse</h2>
<div style="background-color: #199aca; width: auto; padding: 10px 50px;">
    <div style="position: relative; left: 700px; top: -60px; height:0px;">
        <img src="~/Content/image/no-photo.jpg" style="border: 2px solid #fff; width: 382px; height: 334px; border-radius: 80px;">

    </div>
    @using (Html.BeginForm("AddJoueur", "Competition"))
    {
        <div class="form-group">
            <label>Nom </label>
            <input type="text" class="form-control" name="nom">
            <label>Prenom </label>
            <input type="text" class="form-control" name="prenom">
            <label>Sexe </label>
            <select class="form-control" name="sexe">
                <option></option>
                <option>Masculin</option>
                <option>Féminin</option>
            </select>
            <label>Date de naissance</label>
            <input type="date" class="form-control" name="dateNaissance" />
            <label>Nationalité </label>
            @Html.DropDownList("Pays", Session["listePays"] as SelectList, string.Empty, new { @class = "form-control" })

        </div>

        <br />
        <br />
        <input type="submit" class="btn btn-warning" value="Enregistrer" />
        @Html.ActionLink("Annuler", "AjoutParticipant/" + Session["idComp"], "Competition", new { area = "" }, new { @class = "btn btn-danger" })
    }
</div>

basePing/Views/Competition/AddPosition.cshtml
@using basePing.Models
<h2>Classement du joueur dans la compétition</h2>
<br />
<div style="background-color: #199aca; width: auto; padding: 10px 50px;">
    <div class="form-inline">
        @using (Html.BeginForm("FinalizeParticipation", "Competition"))
        {
            <div class="form-group">
                <label>Joueur </label>
                <input type="hidden" class="form-control" name="id" value="@ViewBag.participant.Id">
                <input type="text" disabled="disabled" class="form-control" name="nom" value="@ViewBag.participant.Nom">
            </div>

            <div class="form-group">
                <label>Joueur </label>
                <input type="text" disabled="disabled" class="form-control" value="@ViewBag.participant.Prenom">
            </div>

            <div class="form-group">
                <label>Position</label>
                <select class="form-control" name="position">
                    <option>Pas classé(e)</option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    <option>6</option>
                    <option>7</option>
                    <option>8</option>
                    <option>9</option>
                    <option>10</option>
                    <option>11</option>
                    <option>12</option>

                </select>
            </div>
            <br />
            <br />
            <input type="submit" class="btn btn-success" value="Valider" />
        }
    </div>
    @Html.ActionLink("Annuler", "InfoComp/" + Session["idComp"], new { area = "" }, new { @class = "btn btn-danger" })
</div>

basePing/Views/Competition/AjoutParticipant.cshtml
@using basePing.ViewModel
@{
    ViewBag.Title = "Add Participant";
}

<h2>Ajouter un/des participant(s)</h2>

<div style="background-color: #199aca; width: auto; padding: 10px 50px;">
    <table class="table table-striped">
        <thead>Liste des participant(es)</thead>
        @foreach (VMParticipant j in ViewBag.listeParticipant)
        {
            <tr class="bg-info">
                <td>@j.Nom</td>
                <td>@j.Prenom</td>
                <td>@j.National</td>
                <td>@j.Position</td>
                <td>@Html.ActionLink("Retirer", "SubJoueur", "Competition", new { id = j.Id }, new { @class = "btn btn-danger" })</td>
            </tr>
        }
     </table>
    <div class="form-inline">
        @using (Html.BeginForm("ListeParticipant", "Competition"))
        {
            <div class="form-group">
                <label>Joueur </label>
                <input type="text" class="form-control" name="nom">
            </div>

            <div class="form-group">
                <label>Nationalité </label>
                @Html.DropDownList("Pays", Session["listePays"] as SelectList, string.Empty, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Sexe </label>
                <select class="form-control" name="sexe">
                    <option></option>
                    <option>Masculin</option>
                    <option>Féminin</option>
                </select>
            </div>
            <input type="submit" class="btn btn-warning" value="Recherche" />
        }
    </div>
    <br />
    @Html.ActionLink("Terminé", "InfoComp/" + Session["idComp"], new { area = "" }, new { @class = "btn btn-danger" })
    @Html.ActionLink("Créer un joueur/joueuse", "AddNewJoueur", new { area = "" }, new { @class = "btn btn-success" })
    <div>
        <h2 class="alert-danger">@Request.QueryString["error"]</h2>
    </div>
</div>

basePing/Views/Competition/AjouterSousCatForm.cshtml
@using (Html.BeginForm("AjouterSousCat", "Competition"))
{
    <br />
    <br />
    <label>Nom</label>

    <input type="text" name="nom" required="required" />

    <input type="submit" value="Ajouter" />

}

basePing/Views/Competition/AjouterTypeCompForm.cshtml
 

    @using (Html.BeginForm("AjouterTypeComp", "Competition"))
    {

    <label>Nom</label>

    <input type="text" name="nom" required="required" />
    <label>Description(Optionnel)</label>
    <input type="text" name="desc" height="45"/>

    <input type="submit" value="Ajouter" />

    }

basePing/Views/Competition/ListeParticipant.cshtml
@using basePing.Models;
@using basePing.DataContext;
@{
    ViewBag.Title = "ListeParticipant";
}

<h2>Liste des participants</h2>
<br />
<div style="background-color: #199aca; width: auto; padding: 10px 50px;">

    <div class="form-inline">
        @using (Html.BeginForm("ListeParticipant", "Competition"))
        {
            <div class="form-group">
                <label>Joueur </label>
                <input type="text" class="form-control" name="nom">
            </div>

            <div class="form-group">
                <label>Nationalité </label>
                @Html.DropDownList("Pays", Session["listePays"] as SelectList, string.Empty, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Sexe </label>
                <select class="form-control" name="sexe">
                    <option></option>
                    <option>Masculin</option>
                    <option>Féminin</option>
                </select>
            </div>
            <br />
            <br />
            <input type="submit" class="btn btn-warning" value="Recherche" />
        }
    </div>
    <div>
        <br />
        <table class="table table-striped">
            <thead>Liste de joueur(s)</thead>
            @foreach (Joueur j in ViewBag.listejoueur)
            {
                <tr class="bg-info">
                    <td>@j.Nom</td>
                    <td>@j.Prenom</td>
                    <td>@j.National</td>
                    <td>@Html.ActionLink("Participe", "AddPosition", "Competition", new { id = j.Id }, new { @class = "btn btn-info" })</td>
                </tr>
            }
        </table>
    </div>
    @Html.ActionLink("Créer un joueur/joueuse", "AddNewJoueur", new { area = "" }, new { @class = "btn btn-success" })
    @Html.ActionLink("Annuler", "InfoComp/" + Session["idComp"], new { area = "" }, new { @class = "btn btn-danger" })
</div>

basePing/Views/Competition/ModifCat.cshtml
@using (Html.BeginForm("ModifCat", "Competition"))
{

<input type="hidden" value="@ViewBag.idCat" name="id" />
<label>Nom</label>
<input type="text" name="nom" required="required" />
<label>Descriptif</label>
<input type="text" name="desc" required="required" />

<input type="submit" value="Modifier" />

}

basePing/Views/Competition/ModifSousCatForm.cshtml
@using (Html.BeginForm("ModifSousCat", "Competition"))
{

    <input type="hidden" value="@ViewBag.idSC" name="id" />
    <label>Nom</label>
    <input type="text" name="nom" value="@ViewBag.Nom" required="required" />


    <input type="submit" value="Modifier" />

}

basePing/Views/Competition/ModifierComp.cshtml
@using (Html.BeginForm("ModifierComp", "Competition"))
{

   
    <h1>Modification de la compétition</h1>
    <br />
    <label>Nom de la compétition</label>
    <input type="text" name="nom" value="@ViewBag.Nom" required="required" />
    <label>Date de début </label>
    <input type="date" name="dateD" value="@ViewBag.dateD.ToString("yyyy-MM-dd")" required="required" />
    <label>Date de fin </label>
    <input type="date" name="dateF" value="@ViewBag.dateF.ToString("yyyy-MM-dd")" required="required"/>
    <br />
    <label>Nationalité</label>
    @Html.DropDownList("pays", (SelectList)ViewBag.listePays, new { @class = "form-control" })
    <label>Type compétition</label>
    @Html.DropDownList("type", (SelectList)ViewBag.listeType, new { @class = "form-control" })
    <label>Equipe ou Individuel</label>
    @Html.DropDownList("nbrJ", (SelectList)ViewBag.listeNbrJ, new { @class = "form-control" })
    <label>Sous catégorie</label>
    @Html.DropDownList("idSC", (SelectList)ViewBag.listeSC, new { @class = "form-control" })
    <input type="hidden" value="@ViewBag.idComp" name="idComp" />

    <input type="submit" value="Ajouter Compétition" />

}

basePing/Views/Competition/SousCategorie.cshtml
@using basePing.Models

<br />
<h2>
    @ViewBag.Cat.Nom
    @if ((bool)Session["admin"])
    {
        @Html.ActionLink("Modifier", "ModifCat", "Competition", new { id = ViewBag.Cat.Id }, new { @class = "btn btn-success" })


        if (@ViewBag.Cat.Id >= 4)
        {
            @Html.ActionLink("Supprimer", "SuppCat", "Competition", new { id = ViewBag.Cat.Id }, new { @class = "btn btn-danger", onclick = "return confirm('Attention , la supression de la catégorie entrainera la supression de toutes informations liée à cette dernière, êtes vous sur.')" })
        }
    }
</h2>

<div style="background-color: #199aca; width: auto; padding: 10px 50px;">
    <br />
    <div class="btn-group btn-group-justified">
        <ul style="list-style-type: none; ">

            @foreach (SousCategorie cat in ViewBag.sousCat)
            {
                <li>
                    <a href="~/Competition/GetComp/@cat.Id" class="btn btn-primary">@cat.Nom</a>
                    @if ((bool)Session["admin"])
                {
                        @Html.ActionLink("Modifier", "ModifSousCatForm", "Competition", new { idSC = cat.Id ,nom=cat.Nom}, new { @class = "btn btn-success" })

                        @Html.ActionLink("Supprimer sous catégorie", "SuppSousCat", "Competition",
                   new { idSC = cat.Id },
                    new { @class = "btn btn-danger", onclick = "return confirm('Attention , la supression de la catégorie entrainera la supression de toutes les compétitions ainsi que ces informations liée , êtes vous sur.')" });
                }
                </li>
            }
        </ul>
    </div>
    <br />
    @if ((bool)Session["admin"])
    {

        @Html.ActionLink("Ajouter un type de compétition", "AjouterSousCatForm", "Competition", null, new { @class = "btn btn-success" })
    }
</div>

basePing/Views/Competition/SupressionComp.cshtml
@{
    ViewBag.Title = "SupressionComp";
}

<h2>SupressionComp</h2>

basePing/Views/Competition/getComp.cshtml
@using basePing.Models;


@using (Html.BeginForm("ListComp", "Competition"))
{
    <div class="form-group">
        <label>Nom de la compétition </label>
        <input type="text" class="form-control" name="nom">
    </div>

        <div class="form-group">
            <label>Annnée </label>
            <input type="number" name="an" min="1950" max="2100"/>
        </div>

        <div class="form-group">
            <label>Sexe </label>
            <select class="form-control" name="sexe">
                <option></option>
                <option>Mixte</option>
                <option>Masculin</option>
                <option>Féminin</option>
            </select>
        </div>

        <div class="form-group">
            <label>Type </label>
            <select class="form-control" name="nbrJ">
                <option></option>
                <option>Individuel</option>
                <option>Equipe</option>
            </select>
        </div>
        <br />
        <br />
        <input type="submit" class="btn btn-warning" value="Recherche" />
}
<br />
<h2>Tableau des compétitions</h2>
<div style="background-color: #199aca; width: auto; padding: 10px 50px;">
    <table border="1" class="table table-striped">
        @{
            ((Categorie)ViewBag.cat).GetListSousCat();
            if ((bool)Session["admin"])
            {
                <tr class="bg-info">
                    <td colspan="3">
                        @Html.ActionLink("Crée une nouvelle compétition", "AjoutComp", "Competition",
                    new { id = ViewBag.cat.Id, idSC = Session["idSC"] }, new { @class = "btn btn-info" })

                    </td>
                </tr>
            }
            <tr><th>Compétition</th><th>Date</th><th>Type de la compétition</th><th>Type de rencontre</th><th>Vainqueur</th></tr>


         
            foreach (Competition c in ViewBag.listComp)
            {
                <tr class="bg-info">
                    <td>
                        @Html.ActionLink(c.Nom, "InfoComp", "Competition",
           new { id = c.Id }, new { @class = "btn btn-info" })
                    </td>
                    <td>
                        @c.DateDeb.Year
                    </td>
                    <td>
                        @c.TypeComp
                    </td>
                    <td>
                        @c.NbrJoueur
                    </td>
                    <td>
                        
                            @c.GetVainqueur()

                    </td>

                </tr>
                        }

        }
    </table>
</div>

    